### ISSUE TITLE
Library for Cytron LSA-08 module

### ISSUE THREAD

**Issue by sawhney-medha** [RoboManipal-9-0/Libraries#10]
**Task priority** : HIGH

**Task description**
Library for Cytron LSA08 Module, to make communication with the LSA module hassle free.

**Person assigned** :  @Medhe12 

# Must Haves

- [x] Serial Read function
- [x] Analog Read function
- [x] Raw values for Analog Read
- [x] Flags for LSA values wrt different regions of LSA
- [x] Last non 255 LSA value
- [x] Mode Filtered Values

## References
https://github.com/CytronTechnologies/Arduino-LSA08 https://drive.google.com/file/d/0BzFWfMiqqjyqXzFaMTNHMy1pWUE/view
