### ISSUE TITLE
Library for D45Base for Manual Bot

### ISSUE THREAD

**Issue by shashank3199** [RoboManipal-9-0/Libraries#12]
**Task priority**: HIGH

## Task description
A Library for D45 Configuration of Wheels for the Manual Bot Base.

**Person assigned**: @shashank3199  

# Must Haves
- [x] Name the library: `D45Base`, derive from **BotBase**.
- [x] Fix Equations for the given configuration as Tested in earlier stages.
- [x] Fix Rotate Functionality.
- [x] Serial Test / Example Code.
- [x] Update Documentation.

**Comment by shashank3199** [comment]
Issue Completed.
Ready for Testing.
