### ISSUE TITLE
Cytron PS2 Controller Library

### ISSUE THREAD

**Issue by akshatha-k** [RoboManipal-9-0/Libraries#13]
**Task Priority** : HIGH

** Task Description**
Library for a PS2 Controller to read joystick values and get desired angle and speed for bot motion.

**Person assigned**: @akshatha-k 

Original Cytron PS2 Shield library reference: [here](https://github.com/CytronTechnologies/Cytron_PS2Shield)

## Must Haves
- [x] Initialise software serial
- [x] Function to calculate angle and speed of the desired motion from analog joystick values.
- [x] Function to map the values from a circular space to a square. 
- [x] Compatibility with buttons to expand its function to toggle modes/start/stop etc.
- [x] Have a function that neglects readings from a circular inner region.
- [ ] Compatibility with Other Hardware Serials.

**Comment by akshatha-k** [comment]
Tried to solve the equations to map a square to a circle as the values not lying on the axis were reported to be higher , using the approach followed for a unit square to circle mapping [here](http://mathproofs.blogspot.com/2005/07/mapping-square-to-circle.html)
But the equations for the transformed co-ordinates were solutions of quadratic and bi-quadratic equations respectively. Hence, the code is mapped to modify all values greater than 127 to 127.

**Comment by TheProjectsGuy** [comment]
**Compatibility issues**
- Debugger implementation is out of date, please use the `DebuggerSerial` library from the `dev` branch (link [here](https://github.com/RoboManipal-9-0/Libraries/tree/dev/DebuggerSerial))
- Documentation fixes: 
    - README has no mathematical proof or proper help for code.
    - README points to the `DATA` folder (for image links) that no longer exists on the master or the dev branch. Replace it with _.DATA/Images_ (the folder is now hidden).
