### ISSUE TITLE
Prepare Library for Rhino DC Servo Motor

### ISSUE THREAD

**Issue by shashank3199** [RoboManipal-9-0/Libraries#14]
**Task priority**
HIGH

# Task description
Create Library for Rhino DC Servo RMCS-220X

**Person assigned**
Task assigned to @shashank3199 

# Must Haves
- [x] Abstract Class Implementation
- [x] Serial Interface
- [x] I2C Interface
- [x] Examples
    - [x] Serial Example
    - [x] I2C Example
- [x] Documentation
- [x] Addl Functionalities -
  - [x] Modify P-Gain term for the Encoder
  - [x] Modify I-Gain term for the Encoder
## Extras
- [x] Complete Testing
