### ISSUE TITLE
Design a library for N wheel holonomic drive

### ISSUE THREAD

**Issue by TheProjectsGuy** [RoboManipal-9-0/Libraries#6]
**Task priority**: HIGH

## Task description
A library for N wheel concentric holonomic drive using Omni Wheels

**Person assigned**: @TheProjectsGuy 

# Must Haves
- [x] Name the library: `NWCHBase`, derive from **BotBase**
- [x] Generic implementation of an N omni wheel holonomic drive
- [x] Derive equations for a _**N** wheel concentric holonomic drive_
- [x] Test for 3 and 4 omni wheel bases
- [x] Documentation

**Comment by TheProjectsGuy** [comment]
# Reference derivation
Standard equations must follow the following
![643a6e1c-1290-4486-bfba-0686d51a6787](https://user-images.githubusercontent.com/29420733/46515547-10535300-c882-11e8-901f-2f775ddb7a8f.jpeg)

**Comment by TheProjectsGuy** [comment]
Testing the dev branch code for the base will successfully test this issue and the issue #8 simultaneously.

**Comment by TheProjectsGuy** [comment]
# Testing
## Test 1
Got invalid debugger results
```
[33 DEBUG] $FWBase$ Moved into MOVE function
[1040 DEBUG] $FWBase$ Wheel motion vector: 100.00 54.03 100.00 86.23 
[1481 DEBUG] $FWBase$ Mode: Standard
[1482 DEBUG] $FWBase$ Motor 1 status = [7: 0, 50: 0]
[1484 DEBUG] $FWBase$ Mode: Standard
[1487 DEBUG] $FWBase$ Motor 2 status = [8: 16201, 51: 1]
[1492 DEBUG] $FWBase$ Mode: Standard
[1496 DEBUG] $FWBase$ Motor 3 status = [9: -13340, 52: 1]
[1501 DEBUG] $FWBase$ Mode: Standard
[1505 DEBUG] $FWBase$ Motor 4 status = [10: 16406, 53: 1]
```
Angle configuration is going bogus
```
[7 DEBUG] $FWBase$ Angles : 45 135 225 315 
[11 INFO] $FWBase$ Initializing angle configuration: 45(67.50) 135(202.50) -16384(337.50) 315(472.50) 
```
The second index has some errors, it's actually (upon printing later)
```
[19 DEBUG] $FWBase$ 225
```

## Test 2
Added changes to the conversion and this happened
```
[0] > Debugger enabled
[0] > DebuggerSerial attached
[1] > Debugger set to SENSOR_FEED
[2 DEBUG] $FWBase$ Number of wheels set to 4
[7 DEBUG] $FWBase$ Angles : 45 135 225 315 
[11 INFO] $FWBase$ Initializing angle configuration:  NAN) 135(2.36) 21455(3.93) 315(5.50) 
[18 DEBUG] $FWBase$ 225
[20 INFO] $FWBase$ Motor number 1 attached to (PWM, DIR): 7, 50 Reverse DIR: FALSE
[27 INFO] $FWBase$ Motor number 2 attached to (PWM, DIR): 8, 51 Reverse DIR: FALSE
[34 INFO] $FWBase$ Motor number 3 attached to (PWM, DIR): 9, 52 Reverse DIR: TRUE
[41 INFO] $FWBase$ Motor number 4 attached to (PWM, DIR): 10, 53 Reverse DIR: FALSE
[49 DEBUG] $FWBase$ All pins attached
[52 DEBUG] $FWBase$ MOVE function executing
[56 DEBUG] $FWBase$ Wheel vectors: 0.00, 100.00
[60 DEBUG] $FWBase$ Angle 0 is 0.00 NOW: 4
[64 DEBUG] $FWBase$ Angle 1 is 0.00 NOW: 14
[68 DEBUG] $FWBase$ Wheel motion vector: 100.00 100.00 
```
Conversion from degrees to radians is giving errors. This works however
```ino
Serial.println("DEBUG: ");      // TODO: Remove
float a = 45 * 0.01745329;      // TODO: Remove
Serial.println(a);              // TODO: Remove
```
Giving 
```
DEBUG: 
0.79
```
**Problem assumed**: Angle conversion not happening correctly, checking the `void NWCHBase::InitializeWheels(int *angles_deg)` function
### Code snippet causing problems
Found this is the function
```cpp
this->angles[i] = 45 * 0.01745329;    // Convert angles to radians and assign them     // TODO: Fix
```
When it's uncommented, it gives
```
[11 INFO] $FWBase$ Initializing angle configuration:  NAN) 45(0.79) 45(0.79) 45(0.79) 
```
When commented, it gives (I've initialized everything to _hard 45_)
```
[11 INFO] $FWBase$ Initializing angle configuration: 45(0.79) 45(0.79) 45(0.79) 45(0.79)
```
**Issue fixed**: Did the following
- Using angles in degrees ONLY, and creating a macro `DEG2RAD`.
- Pointer initialization errors fixed
Results
```
[0] > Debugger enabled
[0] > DebuggerSerial attached
[1] > Debugger set to SENSOR_FEED
[2 DEBUG] $FWBase$ Number of wheels set to 4
[7 DEBUG] $FWBase$ Angles : 45 135 225 315 
[11 INFO] $FWBase$ Initializing angle configuration: 45(45) 135(135) 225(225) 315(315) 
[18 DEBUG] $FWBase$ Angles after reading : 45 135 225 315 
[23 INFO] $FWBase$ Motor number 1 attached to (PWM, DIR): 7, 50 Reverse DIR: FALSE
[30 INFO] $FWBase$ Motor number 2 attached to (PWM, DIR): 8, 51 Reverse DIR: FALSE
[37 INFO] $FWBase$ Motor number 3 attached to (PWM, DIR): 9, 52 Reverse DIR: TRUE
[44 INFO] $FWBase$ Motor number 4 attached to (PWM, DIR): 10, 53 Reverse DIR: FALSE
[51 DEBUG] $FWBase$ All pins attached
[54 DEBUG] $FWBase$ MOVE function executing
[59 DEBUG] $FWBase$ Wheel vectors: 0.00, 100.00
[63 DEBUG] $FWBase$ Angle 0 is 45 1 is 135 2 is 225 3 is 315 
[67 DEBUG] $FWBase$ Starting vector calculations
[73 DEBUG] $FWBase$ Wheel motion vector: 70.71 -70.71 -70.71 70.71 
```
Got the correct motion vector at least :satisfied:

### Error on wheel actuation
Actuation part needs fixing
```
[78 DEBUG] $FWBase$ Mode: Standard
[81 DEBUG] $FWBase$ Motor 1 status = [7: 0, 50: 0]
[86 DEBUG] $FWBase$ Mode: Standard
[89 DEBUG] $FWBase$ Motor 2 status = [8: 17037, 51: 1]
[93 DEBUG] $FWBase$ Mode: Standard
[97 DEBUG] $FWBase$ Motor 3 status = [9: -6267, 52: 1]
[101 DEBUG] $FWBase$ Mode: Standard
[104 DEBUG] $FWBase$ Motor 4 status = [10: 454, 53: 1]
```

**Comment by TheProjectsGuy** [comment]
# Issue
Arduino resetting :confused: 
**Maybe**: Pointer accessing something out of code memory of ATMEGA 2560
Will have to change a lot of things done for #8. Probably `VectorTo_PWM_DIR` is causing errors.\
**Error caught**: Pointer accessing data outside memory field. 
Data leak spotted here:
```
this->PWM_values[wheel_number] = abs(vect_value);                   // Magnitude
this->DIR_values[wheel_number] = (vect_value >= 0) ? HIGH : LOW;    // Direction
```

## Solved the issue
Used dynamic memory allocation

**Comment by TheProjectsGuy** [comment]
Tested on `4 wheel holonomic` and `3 wheel holonomic`. Also works on midway changes
