### ISSUE TITLE
Make a DebuggerSerial library for Debugger

### ISSUE THREAD

**Issue by TheProjectsGuy** [RoboManipal-9-0/Libraries#7]
**Task priority**: HIGH

# Task description
Create a library for debugger serial to be used.

**Person assigned**: @TheProjectsGuy 

# Must Haves
- [x] Create the project under the name `DebuggerSerial`.
- [x] Write Debugger code
- [x] Ensure that it works on Hardware and Software serials
- [x] Documentation

## Extras
- ~~Backward compatibility with all the existing low-level libraries~~ Will create a new issue regarding this soon.

**Comment by TheProjectsGuy** [comment]
# Debugger Code
## Task list
- [x] Stream implementation
   - [x] HardwareSerial
   - [x] SoftwareSerial
- [x] Protocol implementation
   - [x] Every message has a _Name_, _Level_ and _output_ message
   - [x] Simple level message protocol
   - [x] Sensor message protocol
- [x] Verification

**Comment by TheProjectsGuy** [comment]
## File structure goals
The following files have to be completed
- [x] DebuggerSerial.h
- [x] DebuggerSerial.cpp
- [x] README.md
- [x] keywords.txt

**Comment by TheProjectsGuy** [comment]
# Priority levels and Protocol implementation
Debugger will have the following priority levels
```cpp
// Debugger Levels
#define SENSOR_FEED 0         // Sensor data feed
#define NOTIFICATION 10       // Notifications about the debugger ONLY 
#define DEBUG 20              // Debugging level messages
#define INFO 30               // Info level messages
#define WARNING 40            // Warning level messages : Work can still go unaffected
#define ERROR 50              // Error messages : Some aspects might not work
#define FATAL 60              // Fatal messages : Some error caused the system to crash
```

### Protocol implemetation
- For `SENSOR_FEED` data
```
[%Timestamp%] $%Name%$ %value%
```
- For `NOTIFICATION` data
```
[%Timestamp%] > %Message%
```
- For other priority levels
```
[%Timestamp% %Level%] $%Name%$ %Message%
```

**Comment by TheProjectsGuy** [comment]
# References
- C++ delegated constructors [here](https://en.wikipedia.org/wiki/C++11#Object_construction_improvement)

**Comment by TheProjectsGuy** [comment]
Debugger implemented [here](https://github.com/RoboManipal-9-0/Libraries/tree/dev/DebuggerSerial). Task finished
