### ISSUE TITLE
Modify BotBase to be used with more motor driver modes

### ISSUE THREAD

**Issue by TheProjectsGuy** [RoboManipal-9-0/Libraries#8]
**Task priority** : HIGH

# Task description
Have modifications made to the BotBase library so that it can be used with more modes in a motor driver. Eg: _giving the PWM to DIR pin and actual PWM on motor driver being HIGH always_.

**Person assigned**: @TheProjectsGuy 

# Phase 1
## Must-Haves
- [x] Mode 2 on Cytron MDD10A motor drivers
    - [x] Giving PWM to DIR mode
- [x] Patch fixes for stronger base level items

### Extras
- [x] DebuggerSerial patch fix

# Phase 2
## Must-Haves
- [x] Remove _MaxMode_
- [x] Add the following drive modes
    - [Lock Anti-Phase Drive](http://www.modularcircuits.com/blog/articles/h-bridge-secrets/lock-anti-phase-drive/)
    - [Sign-magnitude Drive](http://www.modularcircuits.com/blog/articles/h-bridge-secrets/sign-magnitude-drive/)
- [x] Add functionality of a constant ratio given to every pin: in case we want to apply a factor to every wheel.
- [x] Documentation update

**Comment by TheProjectsGuy** [comment]
Requested mode added as `MaxMode`, will update on documentation soon

**Comment by TheProjectsGuy** [comment]
Started `Phase-2` modifications...

**Comment by TheProjectsGuy** [comment]
Phase 2 done. Will start testing. Documentation updated. Creates `avneesh-BotBase-test` branch for testing.

**Comment by TheProjectsGuy** [comment]
- [ ] Add examples for different types of motor modes in the examples folder
