### ISSUE TITLE
Library for ServoChain

### ISSUE THREAD

**Issue by akshatha-k** [RoboManipal-9-0/Libraries#9]
**Task priority**: Low

**Task description**
Servo Chain library consisting of Dynamixels and Pololus in any order. Maximise user control over servo speeds (playtimes for pololus), through additional functions.

**Person assigned**: @akshatha-k 

### **Codes ready . Testing pending.**

# Must Haves
- [x] Series of Dynamixel servos and XYZPololu servos
- [  ] Initialise the servo IDs and their Serials
- [x] Move the smart Servos to a given position at a programmer defined speed
- [x] Move the smart Servos to a given position at a user-defined speed and playtime.
- [ ] Add thorough documentation of using the Roboplus Dynamixel Wizard. 

# Extras
- [ ] Inverse kinematic functions for N links/joints.

## References
Dynamixel library : https://sourceforge.net/projects/dynamixelforarduino/files/?source=navbar
Pololu LIbrary: https://github.com/pololu/xyzrobot-servo-arduino
Robotis Dynamixel Wizard : http://support.robotis.com/en/software/roboplus/dynamixel_monitor.htm
